/**
 * Capability packs — curated bundles of SEMOSS reactors exposed to an agent as
 * tools.
 *
 * ## Why packs and not raw Pixel
 *
 * The `semoss` harness ships 15 native tools and every one of them is a file, a
 * shell command, or a todo. None can call a SEMOSS reactor, so vector search,
 * database queries, frames, git and publishing are all unreachable from inside a
 * run — even though the harness prompt already tells the model to use engine ids
 * and "project-scoped Pixel or tool calls".
 *
 * A `Pixel(code=...)` reactor exists and would hand over the whole platform in one
 * tool, but it gives up everything worth having: per-reactor RBAC still applies
 * either way, yet only named tools can be individually gated behind human approval,
 * and only named tools give the model a real parameter schema instead of making it
 * write Pixel syntax from memory.
 *
 * ## Where a pack actually lives
 *
 * Not here. Each pack is a seeded `platform__pack-*` SKILL project, listed in
 * `SystemDefaultEngines.SYSTEM_MCPS` and cataloged at boot by `ProjectWatcher`,
 * which tags it `MCP` + `SYSTEM`. Its tools are generated by `MakePixelMCP` into
 * `assets/mcp/pixel_mcp.json` — schemas derived from each reactor's own
 * `keysToGet` — and its guidance ships beside them in `assets/public/SKILL.md`.
 *
 * This file used to hold that content as a TypeScript constant, which was the wrong
 * shape three ways: only the harness could see the packs, an admin could not curate
 * one without a frontend rebuild, and the ask/auto approval policy — a security
 * decision — sat in frontend code where it could not be audited or overridden per
 * deployment. Regenerate them with `Semoss/dev-scripts/generate-capability-packs.py`.
 *
 * So enabling a pack is not a special operation: it adds that project to
 * `room.options.mcp`, the same list every other MCP toolbox uses, and the agent
 * picks it up because its tool list is the union of workspace resources and
 * `room.options.mcp[]`. Nothing in this module writes tools.
 *
 * ## Execution mode
 *
 * `auto` runs without asking. `ask` routes through the platform's existing
 * human-in-the-loop path — the run parks in `INPUT_REQUIRED`, an `AGENT_RUN_ACTION`
 * row is written, and the user approves, edits, rejects or answers. The mode is
 * carried per tool in `_meta.SMSS_MCP_EXECUTION` and is read from the pack, never
 * decided here; this module only counts the `ask` tools so the UI can say how many
 * there are.
 */

/**
 * Project-id prefix marking a seeded capability pack.
 *
 * Every pack is an MCP-tagged project, but not every MCP-tagged project is a pack —
 * `room-filesystem` and `reactor-help` are toolboxes the platform attaches for its
 * own reasons. The prefix is what separates "a curated capability someone opts into"
 * from the rest of the toolbox list, and it is fixed by the `Constants.PACK_*` ids.
 */
export const PACK_PROJECT_PREFIX = "pack-";

/** Engine types a pack is useless without. Matches `engine_type`. */
export type PackEngineRequirement = "DATABASE" | "VECTOR" | "MODEL" | "STORAGE";

/** A pack as the UI needs it: identity from the platform, counts from its tools. */
export interface CapabilityPack {
	/** Project id, e.g. `pack-data`. Stable — these are `Constants.PACK_*`. */
	id: string;

	/** Short label for the toggle, derived from the id. */
	label: string;

	/** One line on what the agent gains, from the pack's SKILL.md frontmatter. */
	description: string;

	/** How many tools the pack exposes. */
	toolCount: number;

	/** How many of those pause for a human decision. */
	askCount: number;

	/** Engine types this pack needs attached to be useful. */
	requires?: PackEngineRequirement[];
}

/**
 * Which engine type each pack needs attached, for the "this pack has nothing to
 * point at" warning.
 *
 * A display hint, not policy — the authoritative statement is the `## Prerequisite`
 * section of the pack's own SKILL.md, which is what the agent reads. It is kept here
 * because the fact is a single word per pack and the alternative is fetching and
 * parsing seven SKILL.md files to render one warning icon. A pack missing from this
 * map simply gets no warning.
 */
const PACK_ENGINE_HINTS: Record<string, PackEngineRequirement[]> = {
	"pack-data": ["DATABASE"],
	"pack-knowledge": ["VECTOR"],
	"pack-storage": ["STORAGE"],
};

/**
 * Pack ids as they were before packs became projects.
 *
 * The old frontend constant used bare names (`git`), the projects use prefixed ids
 * (`pack-git`). A room that enabled a pack under the old scheme has the bare name in
 * `options.packs`, which no longer resolves to anything, so it is translated on read
 * rather than left to silently look like "no packs enabled".
 */
const LEGACY_PACK_IDS: Record<string, string> = {
	data: "pack-data",
	rag: "pack-knowledge",
	frames: "pack-frames",
	git: "pack-git",
	publish: "pack-publish",
	storage: "pack-storage",
	browser: "pack-browser",
};

/** Translate a possibly-legacy pack id to its project id. */
export const normalizePackId = (id: string): string =>
	id.startsWith(PACK_PROJECT_PREFIX) ? id : (LEGACY_PACK_IDS[id] ?? id);

/** True when a project id belongs to a capability pack. */
export const isPackProject = (id: string | undefined): boolean =>
	!!id?.startsWith(PACK_PROJECT_PREFIX);

/**
 * `pack-knowledge` → `Knowledge`. The project id is the only name the platform
 * carries for a pack — every seeded project shares the display name `platform` —
 * so the label is derived rather than looked up.
 */
export const packLabel = (id: string): string => {
	const stem = id.startsWith(PACK_PROJECT_PREFIX)
		? id.slice(PACK_PROJECT_PREFIX.length)
		: id;
	return stem.charAt(0).toUpperCase() + stem.slice(1).replace(/-/g, " ");
};

/** One tool as `GetMCPTools` returns it. */
export interface PackTool {
	name?: string;
	_meta?: { SMSS_MCP_EXECUTION?: string };
}

/**
 * Count a pack's tools, splitting out the ones that ask.
 *
 * `SkillMCP` wraps a SKILL-type project's toolbox and appends its own
 * `ListSkillFiles`/`ReadSkillFile`, so the raw list is longer than the pack's
 * curated set. Those two are the mechanism by which the agent reads the pack's
 * guidance, not capabilities the pack grants, so counting them would overstate every
 * pack by two.
 */
const SKILL_MCP_TOOLS = new Set(["ListSkillFiles", "ReadSkillFile"]);

export const summarizePackTools = (
	tools: readonly PackTool[],
): { toolCount: number; askCount: number } => {
	const own = tools.filter((tool) => !SKILL_MCP_TOOLS.has(tool.name ?? ""));
	return {
		toolCount: own.length,
		askCount: own.filter((tool) => tool._meta?.SMSS_MCP_EXECUTION === "ask")
			.length,
	};
};

/** Assemble a pack for display from its project id and served tools. */
export const buildCapabilityPack = (
	id: string,
	description: string,
	tools: readonly PackTool[],
): CapabilityPack => ({
	id,
	label: packLabel(id),
	description,
	requires: PACK_ENGINE_HINTS[id],
	...summarizePackTools(tools),
});
